'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require(process.env.ORDER_TEST_JSDOM || 'jsdom');
const fixtures = process.argv[2];
assert.ok(fixtures, 'Pass fixtures rendered by test_order_share_pickup.write_frontend_fixtures');

function page(name, state = {}, mobile = false) {
    const html = fs.readFileSync(path.join(fixtures, name + '.html'), 'utf8');
    const dom = new JSDOM(html, {url: 'https://share.example.test/share/test-token', runScripts: 'outside-only'});
    const w = dom.window;
    w.scrollTo = () => {};
    w.matchMedia = query => ({matches: mobile && query.includes('max-width')});
    w.requestAnimationFrame = fn => fn();
    w.getTrackingLanguage = () => 'es';
    for (const [key, value] of Object.entries(state)) w.sessionStorage.setItem(key, value);
    const script = Array.from(w.document.querySelectorAll('script')).map(s => s.textContent).find(s => s.includes('const guestToken ='));
    const start = script.indexOf('(function () {\n    const guestToken =');
    const end = script.indexOf('\n})();', start);
    assert.ok(start >= 0 && end > start);
    w.eval(script.slice(start, end + '\n})();'.length));
    const all = () => Array.from(w.document.querySelectorAll('[data-guest-card]'));
    const visible = () => all().filter(c => !c.hidden);
    const logisticsCount = key => w.document.querySelector(`[data-guest-logistics-count="${key}"]`).textContent;
    const statusCount = key => w.document.querySelector(`[data-guest-status-filter="${key}"] small`).textContent;
    const status = key => w.document.querySelector(`[data-guest-status-filter="${key}"]`).click();
    const logistics = key => {
        const radio = w.document.querySelector(`.guest-logistics-radio[value="${key}"]`);
        radio.checked = true;
        radio.dispatchEvent(new w.Event('change', {bubbles: true}));
    };
    return {w, all, visible, logisticsCount, statusCount, status, logistics};
}

const totals = page('all28');
assert.equal(totals.all().length, 28);
assert.equal(totals.statusCount('all'), '28');
assert.equal(totals.logisticsCount('all'), '0');
assert.equal(totals.statusCount('retired'), '28');
assert.equal(totals.w.document.querySelector('.guest-logistics-radio[value="retired"]'), null);
assert.equal(totals.logisticsCount('in_transit'), '0');
assert.equal(totals.logisticsCount('pending_pickup'), '0');
assert.equal(totals.w.document.getElementById('guestVisibleCount').textContent, '28 pedidos');
totals.w.close();

const t = page('sample');
assert.equal(t.statusCount('all'), '7');
assert.equal(t.statusCount('unconfirmed'), '1');
assert.equal(t.statusCount('confirmed'), '2');
assert.equal(t.statusCount('done'), '3');
assert.equal(t.statusCount('retired'), '1');
assert.equal(t.logisticsCount('in_transit'), '2');
assert.equal(t.logisticsCount('pending_pickup'), '1');
assert.equal(t.w.document.querySelector('[data-guest-logistics-count="retired"]'), null);
assert.equal(t.all().filter(c => c.classList.contains('guest-card-retired')).length, 1);
t.logistics('in_transit');
assert.equal(t.visible().length, 2);
assert.equal(t.statusCount('all'), '7');
assert.equal(t.w.document.querySelector('[data-guest-status-filter="all"]').getAttribute('aria-pressed'), 'true');
assert.equal(t.visible().filter(c => c.dataset.guestOrderKey === '1009001-1').length, 1);
t.logistics('pending_pickup');
assert.equal(t.visible().length, 1);
assert.equal(t.visible()[0].dataset.guestOrderKey, '1009001-1');
t.status('retired');
assert.equal(t.visible().length, 1);
assert.equal(t.visible()[0].dataset.guestOrderKey, '1009002-1');
assert.equal(t.w.document.getElementById('guestLogisticsAll').checked, false);
t.status('done');
assert.equal(t.visible().length, 3);
t.logistics('in_transit');
assert.equal(t.visible().length, 2);
assert.equal(t.w.document.querySelector('[data-guest-status-filter="all"]').getAttribute('aria-pressed'), 'true');
t.logistics('all');
assert.equal(t.visible().length, 2);
assert.equal(t.all()[0].dataset.guestOrderKey, '1009005-1');
t.w.document.querySelector('[data-guest-sort="shipping"]').click();
assert.equal(t.all()[0].dataset.guestOrderKey, '1009004-2');
t.w.getTrackingLanguage = () => 'zh_cn';
t.w.document.dispatchEvent(new t.w.CustomEvent('tracking:languagechange'));
assert.equal(t.w.document.getElementById('guestVisibleCount').textContent, '2 个订单');

// Pickup updates rebuild counts and filter membership without reloading the page.
const changed = t.all().find(c => c.dataset.guestOrderKey === '1009003-1');
changed.dataset.guestStatusKey = 'RETIRED';
changed.dataset.guestStatusZh = '已取完';
changed.dataset.guestStatusEs = 'Retirado';
changed.dataset.guestLogisticsKeys = '';
changed.dataset.guestRetired = '1';
changed.classList.add('guest-card-retired');
t.w.document.dispatchEvent(new t.w.CustomEvent('tracking:guestcardsupdated'));
assert.equal(t.statusCount('all'), '7');
assert.equal(t.statusCount('done'), '2');
assert.equal(t.statusCount('retired'), '2');
assert.equal(t.logisticsCount('in_transit'), '2');
assert.equal(t.logisticsCount('pending_pickup'), '1');
assert.equal(t.all()[0].dataset.guestOrderKey, '1009004-2');
t.status('retired');
assert.equal(t.visible().length, 2);
changed.remove();
t.w.document.dispatchEvent(new t.w.CustomEvent('tracking:guestcardsupdated'));
assert.equal(t.statusCount('all'), '6');
assert.equal(t.logisticsCount('all'), '2');
assert.equal(t.visible().length, 1);
t.w.close();

const full = page('full');
assert.equal(full.statusCount('RETIRED'), '1');
full.status('RETIRED');
assert.equal(full.visible().length, 1);
assert.equal(full.visible()[0].dataset.guestRetired, '1');
full.w.close();

const restored = page('sample', {'trackingGuestStatus:test-token': 'retired', 'trackingGuestSort:test-token': 'shipping'});
assert.equal(restored.visible().length, 1);
assert.equal(restored.all()[0].dataset.guestOrderKey, '1009004-2');
restored.w.close();

const counts = page('51-plus-pickup');
assert.equal(counts.all().length, 52);
assert.equal(counts.statusCount('all'), '51');
assert.equal(counts.statusCount('done'), '51');
assert.equal(counts.visible().length, 51);
assert.equal(counts.logisticsCount('all'), '14');
assert.equal(counts.logisticsCount('in_transit'), '13');
assert.equal(counts.logisticsCount('pending_pickup'), '1');
counts.logistics('all');
assert.equal(counts.visible().length, 14);
counts.logistics('pending_pickup');
assert.equal(counts.visible().length, 1);
assert.equal(counts.visible()[0].dataset.guestExtraPickup, '1');
counts.status('all');
assert.equal(counts.visible().length, 51);
let fetches = 0;
counts.w.fetch = () => { fetches++; throw Error('Search must not request the server'); };
const input = counts.w.document.getElementById('guestOrderSearch');
const search = text => { input.value = text; input.dispatchEvent(new counts.w.Event('input', {bubbles:true})); };
search('1008100');
assert.equal(counts.visible().length, 1);
assert.equal(counts.visible()[0].dataset.guestOrderKey, '1008100-1');
assert.equal(counts.statusCount('all'), '51');
assert.equal(counts.logisticsCount('all'), '14');
search('1008100-1');
assert.equal(counts.visible().length, 1);
search('1007000');
assert.equal(counts.visible().length, 0);
assert.equal(counts.w.document.getElementById('guestFilterEmpty').hidden, false);
counts.logistics('pending_pickup');
assert.equal(counts.visible().length, 1);
counts.w.document.dispatchEvent(new counts.w.CustomEvent('tracking:guestcardsupdated'));
assert.equal(input.value, '1007000');
assert.equal(counts.visible().length, 1);
counts.w.getTrackingLanguage = () => 'zh_cn';
counts.w.document.dispatchEvent(new counts.w.CustomEvent('tracking:languagechange'));
assert.equal(input.placeholder, '搜索订单号…');
assert.equal(counts.w.document.getElementById('guestVisibleCount').textContent, '1 个订单');
const savedState = Object.fromEntries(Object.keys(counts.w.sessionStorage).map(k => [k, counts.w.sessionStorage.getItem(k)]));
const restoredSearch = page('51-plus-pickup', savedState);
assert.equal(restoredSearch.visible().length, 1);
assert.equal(restoredSearch.visible()[0].dataset.guestOrderKey, '1007000');
restoredSearch.w.close();
counts.w.document.getElementById('guestOrderSearchClear').click();
assert.equal(input.value, '');
assert.equal(counts.visible().length, 1);
counts.status('all');
assert.equal(counts.visible().length, 51);
search('does-not-exist');
input.dispatchEvent(new counts.w.KeyboardEvent('keydown', {key:'Escape',bubbles:true}));
assert.equal(input.value, '');
assert.equal(counts.visible().length, 51);
assert.equal(fetches, 0);
counts.w.close();
console.log('ORDER pickup UI: counts, split batches, filter reset, sort, language, live refresh and restored state passed');

// The mobile wall stays at five segments even when desktop uses full statuses.
const mobile = page('full', {}, true);
assert.equal(mobile.w.document.querySelectorAll('[data-guest-status-filter]').length, 5);
assert.equal(mobile.statusCount('retired'), '1');
assert.equal(mobile.w.document.querySelector('[data-guest-status-filter="unconfirmed"] span').textContent, 'Sin conf.');
mobile.status('confirmed');
mobile.logistics('in_transit');
assert.equal(mobile.visible().length, 2);
assert.equal(mobile.w.document.querySelector('[data-guest-status-filter="all"]').getAttribute('aria-pressed'), 'true');
assert.ok(mobile.visible().some(c => c.dataset.guestOrderKey === '1009000-1'));
assert.equal(mobile.visible()[0].dataset.guestRetired, '0', 'Partial pickup must never become retired');
const logisticsState = Object.fromEntries(Object.keys(mobile.w.sessionStorage).map(k => [k, mobile.w.sessionStorage.getItem(k)]));
const returned = page('full', logisticsState, true);
assert.equal(returned.visible().length, 2);
assert.ok(returned.visible().some(c => c.dataset.guestOrderKey === '1009000-1'));
returned.w.close();
mobile.w.getTrackingLanguage = () => 'zh_cn';
mobile.w.document.dispatchEvent(new mobile.w.CustomEvent('tracking:languagechange'));
assert.equal(mobile.w.document.querySelector('[data-mobile-text="subtitle"]').textContent, '臨時查看');
assert.equal(mobile.visible().find(c => c.dataset.guestOrderKey === '1009000-1').querySelector('.guest-card-status').textContent, '已确认');
assert.equal(mobile.w.document.querySelector('[data-mobile-logistics="in_transit"]').textContent, '運送中');
assert.equal(mobile.w.document.querySelector('[data-mobile-text="shipping"]').textContent, '出貨日期');
mobile.w.close();
const empty = page('empty', {}, true);
assert.equal(empty.statusCount('all'), '0');
assert.equal(empty.w.document.querySelector('[data-mobile-text="noOrders"]').textContent, 'No hay pedidos disponibles.');
empty.w.close();
console.log('Mobile: five segments, partial shipments, independent logistics restoration, card translations and empty page passed');

const migrated = page('sample', {'trackingGuestStatus:test-token':'retired', 'trackingGuestFilterScope:test-token':'logistics', 'trackingGuestLogistics:test-token':'in_transit'}, true);
assert.equal(migrated.visible().length, 2);
assert.equal(migrated.w.document.querySelector('[data-guest-status-filter="all"]').getAttribute('aria-pressed'), 'true');
migrated.status('unconfirmed');
assert.equal(migrated.visible().length, 1);
assert.equal(migrated.w.document.querySelectorAll('.guest-logistics-radio:checked').length, 0);
migrated.logistics('pending_pickup');
assert.equal(migrated.visible().length, 1);
assert.equal(migrated.visible()[0].dataset.guestOrderKey, '1009001-1');
migrated.w.close();
